export const NOTES = {
  D3: { id: "D3", letter: "D", octave: 3, hz: 146.8324, ding: true },
  A3: { id: "A3", letter: "A", octave: 3, hz: 220 },
  Bb3: { id: "Bb3", letter: "B\u266d", octave: 3, hz: 233.0819 },
  C4: { id: "C4", letter: "C", octave: 4, hz: 261.6256 },
  D4: { id: "D4", letter: "D", octave: 4, hz: 293.6648 },
  E4: { id: "E4", letter: "E", octave: 4, hz: 329.6276 },
  F4: { id: "F4", letter: "F", octave: 4, hz: 349.2282 },
  G4: { id: "G4", letter: "G", octave: 4, hz: 391.9954 },
  A4: { id: "A4", letter: "A", octave: 4, hz: 440 },
  C5: { id: "C5", letter: "C", octave: 5, hz: 523.2511 },
};

export const FIELDS = [
  { id: "C5", deg: 0 },
  { id: "G4", deg: 40 },
  { id: "E4", deg: 80 },
  { id: "C4", deg: 120 },
  { id: "A3", deg: 160 },
  { id: "Bb3", deg: 200 },
  { id: "D4", deg: 240 },
  { id: "F4", deg: 280 },
  { id: "A4", deg: 320 },
];

export const SIDE = {
  D3: "left",
  A3: "right",
  Bb3: "left",
  C4: "right",
  D4: "left",
  E4: "right",
  F4: "left",
  G4: "right",
  A4: "left",
  C5: "right",
};

const L = "left";
const R = "right";

function step(beat, note, hand) {
  return { beat, note, hand };
}

export const PATTERNS = [
  {
    id: "ding-fifth",
    title: "Ding and fifth",
    kind: "Hands",
    bpm: 60,
    loopBeats: 8,
    blurb: "Ding in the center, low A under your right hand.",
    about:
      "Sit with the low A by your right thigh and the B-flat by your left. Left hand plays the ding in the center. Right hand plays the low A. Use the pad of one finger, strike, and lift so the steel can ring.",
    steps: [
      step(0, "D3", L),
      step(2, "A3", R),
      step(4, "D3", L),
      step(6, "A3", R),
    ],
  },
  {
    id: "kurd-color",
    title: "Kurd color",
    kind: "Hands",
    bpm: 72,
    loopBeats: 8,
    blurb: "The half step that makes this scale a Kurd.",
    about:
      "B-flat is the dimple by your left thigh. Play A with the right hand, B-flat with the left, then A again. That half step is the sound of this scale. The ding starts each group of four.",
    steps: [
      step(0, "D3", L),
      step(1, "A3", R),
      step(2, "Bb3", L),
      step(3, "A3", R),
      step(4, "D3", L),
      step(5, "A3", R),
      step(6, "Bb3", L),
      step(7, "A3", R),
    ],
  },
  {
    id: "where-they-sit",
    title: "Where they sit",
    kind: "Hands",
    bpm: 54,
    loopBeats: 12,
    blurb: "Every note, one at a time, so your hands learn the map.",
    about:
      "Play up the scale one note at a time. Right hand climbs A, C, E, G, then the high C at the far rim. Left hand climbs B-flat, D, F, A. Finish on the ding. If a dimple is on the wrong side, turn on Mirror.",
    steps: [
      step(0, "A3", R),
      step(1, "Bb3", L),
      step(2, "C4", R),
      step(3, "D4", L),
      step(4, "E4", R),
      step(5, "F4", L),
      step(6, "G4", R),
      step(7, "A4", L),
      step(8, "C5", R),
      step(9, "D3", L),
    ],
  },
  {
    id: "pass-across",
    title: "Pass it across",
    kind: "Hands",
    bpm: 56,
    loopBeats: 4,
    blurb: "One dimple on each side, back and forth.",
    about:
      "C is on the right, just up from the low A. D is on the left, just up from the B-flat. Play C, D, C, D. Right, left, right, left. Keep every note the same length. Count 1 2 3 4 until the hand change is automatic.",
    steps: [
      step(0, "C4", R),
      step(1, "D4", L),
      step(2, "C4", R),
      step(3, "D4", L),
    ],
  },
  {
    id: "one-stays",
    title: "One hand stays",
    kind: "Hands",
    bpm: 64,
    loopBeats: 8,
    blurb: "Left hand holds B-flat. Right hand walks C, E, G, E.",
    about:
      "Leave the left hand on B-flat, the dimple by your left thigh. It plays on 1 and on 3. The right hand answers on 2 and on 4: C, then E, then G, then E again. The left hand is the clock. Only the right hand changes notes.",
    steps: [
      step(0, "Bb3", L),
      step(1, "C4", R),
      step(2, "Bb3", L),
      step(3, "E4", R),
      step(4, "Bb3", L),
      step(5, "G4", R),
      step(6, "Bb3", L),
      step(7, "E4", R),
    ],
  },
  {
    id: "two-places",
    title: "Two Ds, two As",
    kind: "Hands",
    bpm: 66,
    loopBeats: 8,
    blurb: "Find the octave of D and the octave of A.",
    about:
      "D is in the center and again on the left, one place up from B-flat. A is by your right thigh and again high on the left. Both Ds stay in the left hand. Low A is the right hand, and the high A is the left hand. Listen for the same note an octave up.",
    steps: [
      step(0, "D3", L),
      step(2, "D4", L),
      step(4, "A3", R),
      step(6, "A4", L),
    ],
  },
  {
    id: "right-side",
    title: "Right side",
    kind: "Hands",
    bpm: 80,
    loopBeats: 8,
    blurb: "A walk up the dimples on your right.",
    about:
      "Left hand plays the ding at the start of each bar and lets it ring. Right hand walks A, C, E, G, reaches the high C, and walks back down. Keep one finger and a quiet wrist.",
    steps: [
      step(0, "D3", L),
      step(0, "A3", R),
      step(1, "C4", R),
      step(2, "E4", R),
      step(3, "G4", R),
      step(4, "D3", L),
      step(4, "C5", R),
      step(5, "G4", R),
      step(6, "E4", R),
      step(7, "A3", R),
    ],
  },
  {
    id: "left-side",
    title: "Left side",
    kind: "Hands",
    bpm: 80,
    loopBeats: 8,
    blurb: "A walk up the dimples on your left.",
    about:
      "Right hand plays the low A at the start of each bar and lets it ring. Left hand walks B-flat, D, F, and the high A, then comes back down. B-flat, D, and F are the B-flat chord. The high A is the seventh.",
    steps: [
      step(0, "A3", R),
      step(0, "Bb3", L),
      step(1, "D4", L),
      step(2, "F4", L),
      step(3, "A4", L),
      step(4, "A3", R),
      step(4, "A4", L),
      step(5, "F4", L),
      step(6, "D4", L),
      step(7, "Bb3", L),
    ],
  },
  {
    id: "small-turn",
    title: "Small turn",
    kind: "Grooves",
    bpm: 76,
    loopBeats: 8,
    blurb: "Two bars you can sit on.",
    about:
      "Bar one is the Kurd color. Bar two goes to C on the right and D on the left, then low A, then the ding. Loop both bars until the second one is as calm as the first.",
    steps: [
      step(0, "D3", L),
      step(1, "A3", R),
      step(2, "Bb3", L),
      step(3, "A3", R),
      step(4, "C4", R),
      step(5, "D4", L),
      step(6, "A3", R),
      step(7, "D3", L),
    ],
  },
  {
    id: "let-it-ring",
    title: "Let it ring",
    kind: "Grooves",
    bpm: 60,
    loopBeats: 8,
    blurb: "The silence is part of the pattern.",
    about:
      "Play the ding and the low A together, then wait. The empty beats are the pattern. B-flat answers, then D, then the high A, then the high C. Leave the space empty.",
    steps: [
      step(0, "D3", L),
      step(0, "A3", R),
      step(3, "Bb3", L),
      step(4, "D4", L),
      step(6, "A4", L),
      step(7, "C5", R),
    ],
  },
  {
    id: "lap-groove",
    title: "Lap groove",
    kind: "Grooves",
    bpm: 72,
    loopBeats: 4,
    blurb: "A four-beat pattern with quick notes on the ands.",
    about:
      'Count "1, 2, 3 and, 4 and". On 1, ding and low A together. On 2, B-flat. On 3, D on the left, and on the and a quick E on the right. On 4, low A, then C on the and. Both of those are the right hand.',
    steps: [
      step(0, "D3", L),
      step(0, "A3", R),
      step(1, "Bb3", L),
      step(2, "D4", L),
      step(2.5, "E4", R),
      step(3, "A3", R),
      step(3.5, "C4", R),
    ],
  },
  {
    id: "call-return",
    title: "Call and return",
    kind: "Pieces",
    bpm: 80,
    loopBeats: 16,
    blurb: "Climb one side, then the other, then come home.",
    about:
      "Ding, then A, C, and E on the right. The left hand answers with the ding, then climbs B-flat, D, F, and the high A. The right hand walks down G, E, C, and low A. The phrase closes B-flat, A, ding. Slow the tempo while the jumps are new.",
    steps: [
      step(0, "D3", L),
      step(1, "A3", R),
      step(2, "C4", R),
      step(3, "E4", R),
      step(4, "D3", L),
      step(5, "Bb3", L),
      step(6, "D4", L),
      step(7, "F4", L),
      step(8, "A4", L),
      step(9, "G4", R),
      step(10, "E4", R),
      step(11, "C4", R),
      step(12, "A3", R),
      step(13, "Bb3", L),
      step(14, "A3", R),
      step(15, "D3", L),
    ],
  },
  {
    id: "up-and-back",
    title: "Up and back",
    kind: "Hands",
    bpm: 66,
    loopBeats: 8,
    blurb: "Five steps up, then turn around before F.",
    about:
      "Start on low A with the right hand. Alternate hands up the scale: A, B-flat, C, D, E. Come back down D, C, B-flat. When the loop starts again, the right hand steps from B-flat to low A. This one stops at E on purpose.",
    steps: [
      step(0, "A3", R),
      step(1, "Bb3", L),
      step(2, "C4", R),
      step(3, "D4", L),
      step(4, "E4", R),
      step(5, "D4", L),
      step(6, "C4", R),
      step(7, "Bb3", L),
    ],
  },
  {
    id: "minor-home",
    title: "D minor",
    kind: "Chords",
    bpm: 66,
    loopBeats: 4,
    blurb: "The home chord, rolled because D and F share a hand.",
    about:
      "D, F, and A are D minor, the chord this pan is built on. Ding and low A together, then F, then the higher D, then low A. D and F are both on your left, so they take turns.",
    steps: [
      step(0, "D3", L),
      step(0, "A3", R),
      step(1, "F4", L),
      step(2, "D4", L),
      step(3, "A3", R),
    ],
  },
  {
    id: "a-minor",
    title: "A minor",
    kind: "Chords",
    bpm: 72,
    loopBeats: 4,
    blurb: "High A under the left hand, high C and E under the right.",
    about:
      "A, C, and E are A minor. High A and high C can sound together: high C is the third above that A, and they sit on opposite hands. High A and E can sound together too. E sits below the high A, because this pan has no E above it.",
    steps: [
      step(0, "A4", L),
      step(0, "C5", R),
      step(1, "E4", R),
      step(2, "A4", L),
      step(2, "E4", R),
      step(3, "C5", R),
    ],
  },
  {
    id: "f-under",
    title: "F underneath",
    kind: "Chords",
    bpm: 66,
    loopBeats: 8,
    blurb: "F stays on the left. The right hand answers with C, then A.",
    about:
      "F, A, and C are F major. F is on the left, so it can sound with the high C, and it can sound with the low A. Both of those are on the right. The high A is also on the left, so it cannot join the F. Play F with high C, rest, F with low A, rest, and the same again.",
    steps: [
      step(0, "F4", L),
      step(0, "C5", R),
      step(2, "F4", L),
      step(2, "A3", R),
      step(4, "F4", L),
      step(4, "C5", R),
      step(6, "F4", L),
      step(6, "A3", R),
    ],
  },
  {
    id: "g-minor",
    title: "G minor",
    kind: "Chords",
    bpm: 66,
    loopBeats: 8,
    blurb: "G on the right, with D and then B-flat on the left.",
    about:
      "G, B-flat, and D are G minor. G is on the right. D and B-flat are both on the left, so they take turns under the G. Play the higher D with G, rest, then B-flat with G, and repeat.",
    steps: [
      step(0, "D4", L),
      step(0, "G4", R),
      step(2, "Bb3", L),
      step(2, "G4", R),
      step(4, "D4", L),
      step(4, "G4", R),
      step(6, "Bb3", L),
      step(6, "G4", R),
    ],
  },
  {
    id: "three-and-two",
    title: "Three, three, two",
    kind: "Grooves",
    bpm: 72,
    loopBeats: 4,
    blurb: "Eight quick notes, grouped three, three, and two.",
    about:
      "Play every half beat. The groups are ding, A, A, then ding, A, A, then ding, A. That is three notes, three notes, and two notes. Only the ding and the low A. The hands go left, right, right, left, right, right, left, right.",
    steps: [
      step(0, "D3", L),
      step(0.5, "A3", R),
      step(1, "A3", R),
      step(1.5, "D3", L),
      step(2, "A3", R),
      step(2.5, "A3", R),
      step(3, "D3", L),
      step(3.5, "A3", R),
    ],
  },
  {
    id: "together-split",
    title: "Together, then split",
    kind: "Grooves",
    bpm: 76,
    loopBeats: 8,
    blurb: "Both hands together, then one note each.",
    about:
      "Both hands play together, then they take turns. Ding and low A, then E on the right, B-flat on the left, C on the right. Same hand order from a new pair: ding with G, then E, F, and low A.",
    steps: [
      step(0, "D3", L),
      step(0, "A3", R),
      step(1, "E4", R),
      step(2, "Bb3", L),
      step(3, "C4", R),
      step(4, "D3", L),
      step(4, "G4", R),
      step(5, "E4", R),
      step(6, "F4", L),
      step(7, "A3", R),
    ],
  },
  {
    id: "long-short-long",
    title: "Long, short, long",
    kind: "Grooves",
    bpm: 76,
    loopBeats: 4,
    blurb: "One long note, three quick notes, then a note on 4.",
    about:
      'Count "1 and 2 and 3 and 4 and". On 1, F and G together, and let them hold through the and. Then three quick notes: D, E, B-flat. Those are 2, the and of 2, and 3. Leave the and of 3 empty. On 4, C. The hands go both, left, right, left, right.',
    steps: [
      step(0, "F4", L),
      step(0, "G4", R),
      step(1, "D4", L),
      step(1.5, "E4", R),
      step(2, "Bb3", L),
      step(3, "C4", R),
    ],
  },
  {
    id: "skip-neighbor",
    title: "Skip the neighbor",
    kind: "Hands",
    bpm: 64,
    loopBeats: 16,
    blurb: "Two notes in one hand, and they are not neighbors.",
    about:
      "Each hand plays two beats, then the other hand plays two. The second note skips the dimple in between: low A to E, B-flat to F, C to G, D to the high A, E to the high C. Then the same skips come back down. Leave the skipped dimple silent.",
    steps: [
      step(0, "A3", R),
      step(1, "E4", R),
      step(2, "Bb3", L),
      step(3, "F4", L),
      step(4, "C4", R),
      step(5, "G4", R),
      step(6, "D4", L),
      step(7, "A4", L),
      step(8, "E4", R),
      step(9, "C5", R),
      step(10, "F4", L),
      step(11, "Bb3", L),
      step(12, "G4", R),
      step(13, "C4", R),
      step(14, "A4", L),
      step(15, "D4", L),
    ],
  },
  {
    id: "son-on-the-rim",
    title: "Son on the rim",
    kind: "Hands",
    bpm: 76,
    loopBeats: 32,
    blurb: "Son clave in the left hand. A new dimple every eight beats.",
    about:
      "The left hand plays son clave on one dimple: 1, the and of 2, and 4, then 2 and 3 of the next bar. First the dimple is B-flat, then D, then F, then the high A. The right hand fills the beats in between, and it joins the left hand on 1 of each eight.",
    steps: [
      step(0, "Bb3", L),
      step(0, "G4", R),
      step(1, "E4", R),
      step(1.5, "Bb3", L),
      step(2, "C5", R),
      step(3, "Bb3", L),
      step(4, "A3", R),
      step(5, "Bb3", L),
      step(6, "Bb3", L),
      step(7, "E4", R),
      step(8, "D4", L),
      step(8, "A3", R),
      step(9, "C4", R),
      step(9.5, "D4", L),
      step(10, "E4", R),
      step(11, "D4", L),
      step(12, "C5", R),
      step(13, "D4", L),
      step(14, "D4", L),
      step(15, "G4", R),
      step(16, "F4", L),
      step(16, "C4", R),
      step(17, "A3", R),
      step(17.5, "F4", L),
      step(18, "G4", R),
      step(19, "F4", L),
      step(20, "E4", R),
      step(21, "F4", L),
      step(22, "F4", L),
      step(23, "C5", R),
      step(24, "A4", L),
      step(24, "A3", R),
      step(25, "C4", R),
      step(25.5, "A4", L),
      step(26, "E4", R),
      step(27, "A4", L),
      step(28, "G4", R),
      step(29, "A4", L),
      step(30, "A4", L),
      step(31, "C5", R),
    ],
  },
  {
    id: "nothing-to-grab",
    title: "Nothing to grab",
    kind: "Chords",
    bpm: 72,
    loopBeats: 16,
    blurb: "B-flat and C. Neither chord has a pair you can strike together.",
    about:
      "B-flat is B-flat, D, and F, all on the left, plus the ding. C is C, E, G, and the high C, all on the right. One note per beat. Both A's stay silent. The second time, each chord comes back down.",
    steps: [
      step(0, "Bb3", L),
      step(1, "D4", L),
      step(2, "F4", L),
      step(3, "D3", L),
      step(4, "C4", R),
      step(5, "E4", R),
      step(6, "G4", R),
      step(7, "C5", R),
      step(8, "F4", L),
      step(9, "Bb3", L),
      step(10, "D4", L),
      step(11, "D3", L),
      step(12, "C5", R),
      step(13, "G4", R),
      step(14, "E4", R),
      step(15, "C4", R),
    ],
  },
  {
    id: "minor-door",
    title: "Minor door",
    kind: "Chords",
    bpm: 60,
    loopBeats: 32,
    blurb: "D minor, C, B-flat, then C again. Each one across eight beats.",
    about:
      "D minor first. Low A stays in the right hand. D and F share the left, so they take turns, with the high A and the ding in the roll. C is next, and C, E, G, and the high C are all on the right, so they take turns around the ding. B-flat is only a left-hand roll, with the high C answering from the right. The last eight beats are C again, in a new order, and the ding closes it.",
    steps: [
      step(0, "F4", L),
      step(0, "A3", R),
      step(1, "D4", L),
      step(2, "A4", L),
      step(3, "D3", L),
      step(4, "A3", R),
      step(5, "F4", L),
      step(6, "D4", L),
      step(6, "A3", R),
      step(7, "D3", L),
      step(8, "C5", R),
      step(9, "G4", R),
      step(10, "E4", R),
      step(11, "D3", L),
      step(12, "C4", R),
      step(13, "E4", R),
      step(14, "G4", R),
      step(15, "D3", L),
      step(16, "F4", L),
      step(17, "Bb3", L),
      step(18, "D4", L),
      step(19, "C5", R),
      step(20, "F4", L),
      step(21, "D3", L),
      step(22, "Bb3", L),
      step(23, "D4", L),
      step(23, "C5", R),
      step(24, "G4", R),
      step(25, "C4", R),
      step(26, "D3", L),
      step(26, "E4", R),
      step(27, "C5", R),
      step(28, "E4", R),
      step(29, "G4", R),
      step(30, "C4", R),
      step(31, "D3", L),
    ],
  },
  {
    id: "late-ding",
    title: "Late ding",
    kind: "Grooves",
    bpm: 76,
    loopBeats: 32,
    blurb: "Beat 3 of every bar is empty, and the ding lands on 4.",
    about:
      "Count 1, 2, 3, 4. Play 1, 2, and 4. The right hand takes 1. B-flat takes every 2. On the odd bars the high A takes 4. On the even bars the ding takes 4, alone. The empty 3 is the left hand moving from B-flat to that higher note.",
    steps: [
      step(0, "A3", R),
      step(1, "Bb3", L),
      step(3, "A4", L),
      step(4, "C4", R),
      step(5, "Bb3", L),
      step(7, "D3", L),
      step(8, "A3", R),
      step(9, "Bb3", L),
      step(11, "A4", L),
      step(12, "E4", R),
      step(13, "Bb3", L),
      step(15, "D3", L),
      step(16, "C4", R),
      step(17, "Bb3", L),
      step(19, "A4", L),
      step(20, "E4", R),
      step(21, "Bb3", L),
      step(23, "D3", L),
      step(24, "G4", R),
      step(25, "Bb3", L),
      step(27, "A4", L),
      step(28, "C4", R),
      step(29, "Bb3", L),
      step(31, "D3", L),
    ],
  },
  {
    id: "tresillo-colors",
    title: "Tresillo colors",
    kind: "Grooves",
    bpm: 88,
    loopBeats: 16,
    blurb: "Three hits a bar, and a different color each bar.",
    about:
      "Count 1, the and of 2, and 4. Both hands play on 1. Bar 1 is the ding with low A, then F, then E. Bar 2 is B-flat with G, then D, then the high C. Bar 3 is F with C, then the high A, then E. Bar 4 is D with G, then B-flat, then low A.",
    steps: [
      step(0, "D3", L),
      step(0, "A3", R),
      step(1.5, "F4", L),
      step(3, "E4", R),
      step(4, "Bb3", L),
      step(4, "G4", R),
      step(5.5, "D4", L),
      step(7, "C5", R),
      step(8, "F4", L),
      step(8, "C4", R),
      step(9.5, "A4", L),
      step(11, "E4", R),
      step(12, "D4", L),
      step(12, "G4", R),
      step(13.5, "Bb3", L),
      step(15, "A3", R),
    ],
  },
  {
    id: "habanera-ring",
    title: "Habanera ring",
    kind: "Grooves",
    bpm: 80,
    loopBeats: 32,
    blurb: "Long, short, long, long, through D minor, B-flat, F, and C.",
    about:
      "Every bar is 1, the and of 2, 3, and 4. The first two bars sit on D: the higher D with low A, then a step away and back, then down to the ding. The next two bars roll B-flat on the left while the right hand answers. Then F with C, a bar that trades F and the right hand, a bar on G, and a last bar down to the ding.",
    steps: [
      step(0, "D4", L),
      step(0, "A3", R),
      step(1.5, "E4", R),
      step(2, "F4", L),
      step(3, "E4", R),
      step(4, "C4", R),
      step(5.5, "D4", L),
      step(6, "A3", R),
      step(7, "D3", L),
      step(8, "Bb3", L),
      step(9.5, "C5", R),
      step(10, "D4", L),
      step(11, "G4", R),
      step(12, "C5", R),
      step(13.5, "F4", L),
      step(14, "A3", R),
      step(15, "Bb3", L),
      step(16, "F4", L),
      step(16, "C4", R),
      step(17.5, "A3", R),
      step(18, "A4", L),
      step(19, "C5", R),
      step(20, "C4", R),
      step(21.5, "F4", L),
      step(22, "E4", R),
      step(23, "F4", L),
      step(24, "D3", L),
      step(24, "G4", R),
      step(25.5, "E4", R),
      step(26, "Bb3", L),
      step(27, "C4", R),
      step(28, "A3", R),
      step(29.5, "F4", L),
      step(30, "E4", R),
      step(31, "D3", L),
    ],
  },
  {
    id: "long-turn",
    title: "The long turn",
    kind: "Pieces",
    bpm: 68,
    loopBeats: 32,
    blurb: "The same eight-beat arch, once low, once on G, then home.",
    about:
      "Phrase one is an arch on D. The ding and the low A together, then D, C, B-flat, low A, and back up B-flat, C, D. Phrase two is that arch moved onto G. Phrase three is F with low A, C, B-flat with G, D, high A with E, then C, G, and F. Phrase four is the first arch again, and it ends on the ding.",
    steps: [
      step(0, "D3", L),
      step(0, "A3", R),
      step(1, "D4", L),
      step(2, "C4", R),
      step(3, "Bb3", L),
      step(4, "A3", R),
      step(5, "Bb3", L),
      step(6, "C4", R),
      step(7, "D4", L),
      step(8, "D3", L),
      step(8, "G4", R),
      step(9, "G4", R),
      step(10, "F4", L),
      step(11, "E4", R),
      step(12, "D4", L),
      step(13, "E4", R),
      step(14, "F4", L),
      step(15, "G4", R),
      step(16, "F4", L),
      step(16, "A3", R),
      step(17, "C4", R),
      step(18, "Bb3", L),
      step(18, "G4", R),
      step(19, "D4", L),
      step(20, "A4", L),
      step(20, "E4", R),
      step(21, "C4", R),
      step(22, "G4", R),
      step(23, "F4", L),
      step(24, "D3", L),
      step(24, "A3", R),
      step(25, "D4", L),
      step(26, "C4", R),
      step(27, "Bb3", L),
      step(28, "A3", R),
      step(29, "Bb3", L),
      step(30, "C4", R),
      step(31, "D3", L),
    ],
  },
  {
    id: "ask-then-land",
    title: "Ask, then land",
    kind: "Pieces",
    bpm: 76,
    loopBeats: 32,
    blurb: "Two questions that stop on C. The answers come back to the ding.",
    about:
      "The first question runs low A, D, F, G on the and, and the high A, then G, F, a rest, E on the and, and C. The answer rises through E and F, then comes down to the ding. The next question sits higher and stops on the high C at the rim. The last phrase walks from the high A down to the ding, and the low A joins it.",
    steps: [
      step(0, "A3", R),
      step(1, "D4", L),
      step(2, "F4", L),
      step(2.5, "G4", R),
      step(3, "A4", L),
      step(4, "G4", R),
      step(5, "F4", L),
      step(6.5, "E4", R),
      step(7, "C4", R),
      step(8, "D4", L),
      step(8, "A3", R),
      step(9, "Bb3", L),
      step(10, "C4", R),
      step(10.5, "D4", L),
      step(11, "E4", R),
      step(12, "F4", L),
      step(12, "C4", R),
      step(13, "E4", R),
      step(14, "D4", L),
      step(15, "D3", L),
      step(16, "Bb3", L),
      step(16, "G4", R),
      step(17, "A4", L),
      step(18, "C5", R),
      step(18.5, "A4", L),
      step(19, "G4", R),
      step(20, "F4", L),
      step(20, "C5", R),
      step(21, "E4", R),
      step(22, "G4", R),
      step(23, "C5", R),
      step(24, "A4", L),
      step(24, "E4", R),
      step(25, "G4", R),
      step(26, "F4", L),
      step(26.5, "E4", R),
      step(27, "D4", L),
      step(28, "C4", R),
      step(29, "Bb3", L),
      step(30, "A3", R),
      step(31, "D3", L),
      step(31, "A3", R),
    ],
  },
  {
    id: "four-chords-back",
    title: "Four chords, then home",
    kind: "Pieces",
    bpm: 64,
    loopBeats: 32,
    blurb: "D minor, C, B-flat, and G minor, then a higher middle, then home.",
    about:
      "Four beats to a chord. D minor is the ding with low A, then C, D, and F with low A. C starts as B-flat with C, then E, G, and the high C, because those three sit on the right. B-flat, D, and F take turns on the left under a C. G minor is G with B-flat, then D, G with the ding, and low A. Eight beats leave that loop, reach the high C, and come back down. The opening D minor comes back, then D, low A, B-flat, and the ding.",
    steps: [
      step(0, "D3", L),
      step(0, "A3", R),
      step(1, "C4", R),
      step(2, "D4", L),
      step(3, "F4", L),
      step(3, "A3", R),
      step(4, "Bb3", L),
      step(4, "C4", R),
      step(5, "E4", R),
      step(6, "G4", R),
      step(7, "C5", R),
      step(8, "Bb3", L),
      step(9, "D4", L),
      step(9, "C4", R),
      step(10, "F4", L),
      step(11, "Bb3", L),
      step(11, "C4", R),
      step(12, "Bb3", L),
      step(12, "G4", R),
      step(13, "D4", L),
      step(14, "D3", L),
      step(14, "G4", R),
      step(15, "A3", R),
      step(16, "A4", L),
      step(16, "E4", R),
      step(17, "G4", R),
      step(17.5, "F4", L),
      step(18, "Bb3", L),
      step(18, "G4", R),
      step(19, "A4", L),
      step(20, "C5", R),
      step(20.5, "A4", L),
      step(21, "D4", L),
      step(21, "G4", R),
      step(22, "F4", L),
      step(22, "C4", R),
      step(23, "E4", R),
      step(24, "D3", L),
      step(24, "A3", R),
      step(25, "C4", R),
      step(26, "D4", L),
      step(27, "F4", L),
      step(27, "A3", R),
      step(28, "D4", L),
      step(29, "A3", R),
      step(30, "Bb3", L),
      step(31, "D3", L),
    ],
  },
  {
    id: "hold-then-weave",
    title: "Hold, then weave",
    kind: "Pieces",
    bpm: 72,
    loopBeats: 24,
    blurb: "Eight beats with a gap on 2, a woven middle, then those eight beats again.",
    about:
      "Count 1, the and of 2, 3, 4. D, then E, then F, then D with the low A. Next, C, B-flat on the and, low A, and the ding. The middle eight is a weave: the hands trade every half beat, then a few pairs. The first eight beats return, and the last ding sounds with the low A.",
    steps: [
      step(0, "D4", L),
      step(1.5, "E4", R),
      step(2, "F4", L),
      step(3, "D4", L),
      step(3, "A3", R),
      step(4, "C4", R),
      step(5.5, "Bb3", L),
      step(6, "A3", R),
      step(7, "D3", L),
      step(8, "C4", R),
      step(8.5, "Bb3", L),
      step(9, "E4", R),
      step(9.5, "D4", L),
      step(10, "G4", R),
      step(10.5, "F4", L),
      step(11, "C5", R),
      step(11.5, "D4", L),
      step(12, "Bb3", L),
      step(12, "G4", R),
      step(13, "F4", L),
      step(13, "C4", R),
      step(13.5, "D4", L),
      step(14, "E4", R),
      step(14.5, "F4", L),
      step(15, "D3", L),
      step(15, "G4", R),
      step(16, "D4", L),
      step(17.5, "E4", R),
      step(18, "F4", L),
      step(19, "D4", L),
      step(19, "A3", R),
      step(20, "C4", R),
      step(21.5, "Bb3", L),
      step(22, "A3", R),
      step(23, "D3", L),
      step(23, "A3", R),
    ],
  },
  {
    id: "arrives-on-d",
    title: "Arrives on D",
    kind: "Pieces",
    bpm: 72,
    loopBeats: 32,
    blurb: "Eight bars, none repeated, ending on the higher D.",
    about:
      "Start on the higher D, not the ding. The ding comes once, on 1 of bar 3, and it is alone. No bar comes back. The last two notes are the high A and then the higher D, both in the left hand.",
    steps: [
      step(0, "D4", L),
      step(1, "C4", R),
      step(2, "Bb3", L),
      step(3, "G4", R),
      step(4, "A4", L),
      step(5, "C5", R),
      step(6, "F4", L),
      step(7, "E4", R),
      step(8, "D3", L),
      step(9, "E4", R),
      step(10, "Bb3", L),
      step(11, "C4", R),
      step(12, "D4", L),
      step(13, "E4", R),
      step(14, "F4", L),
      step(15, "C4", R),
      step(16, "Bb3", L),
      step(17, "G4", R),
      step(18, "D4", L),
      step(19, "C5", R),
      step(20, "A4", L),
      step(21, "E4", R),
      step(22, "F4", L),
      step(23, "A3", R),
      step(24, "D4", L),
      step(25, "A3", R),
      step(26, "Bb3", L),
      step(27, "E4", R),
      step(28, "F4", L),
      step(29, "G4", R),
      step(30, "A4", L),
      step(31, "D4", L),
    ],
  },
  {
    id: "night-path",
    title: "Night path",
    kind: "Pieces",
    bpm: 64,
    loopBeats: 32,
    blurb: "Eight bars. Leave D minor, pass G and A, come home.",
    about:
      "The higher D and the low A start together. The line steps to F and E, then moves off D through C and B-flat. Two bars lean on G, with B-flat and G together. The next two open on both A's, high and low. The last two come home: F with the low A, up to the high C, and both hands land on the ding and the low A.",
    steps: [
      step(0, "D4", L),
      step(0, "A3", R),
      step(1, "F4", L),
      step(2, "E4", R),
      step(3, "D4", L),
      step(4, "C4", R),
      step(5, "D4", L),
      step(6, "Bb3", L),
      step(7, "A3", R),
      step(8, "Bb3", L),
      step(8, "G4", R),
      step(9, "D4", L),
      step(10, "C5", R),
      step(11, "Bb3", L),
      step(12, "A4", L),
      step(13, "G4", R),
      step(14, "F4", L),
      step(15, "Bb3", L),
      step(16, "A4", L),
      step(16, "A3", R),
      step(17, "C5", R),
      step(18, "E4", R),
      step(19, "C4", R),
      step(20, "A3", R),
      step(21, "D4", L),
      step(22, "E4", R),
      step(22.5, "F4", L),
      step(23, "E4", R),
      step(24, "F4", L),
      step(24, "A3", R),
      step(25, "G4", R),
      step(26, "A4", L),
      step(27, "C5", R),
      step(28, "G4", R),
      step(29, "F4", L),
      step(30, "E4", R),
      step(31, "D3", L),
      step(31, "A3", R),
    ],
  },
  {
    id: "twinkle",
    title: "Twinkle, twinkle",
    kind: "Pieces",
    bpm: 84,
    loopBeats: 48,
    blurb: "The French air, in C. Every note is already on this pan.",
    about:
      "Six phrases of eight beats. Phrase one is C, C, G, G, A, A, and a G that rings. Phrase two is F, F, E, E, D, D, and a C that rings. Phrases three and four step down from G to a D that rings. Phrases five and six repeat the first two. Nothing was moved. C, E, and G are the right hand. D, F, and A are the left.",
    steps: [
      step(0, "C4", R),
      step(1, "C4", R),
      step(2, "G4", R),
      step(3, "G4", R),
      step(4, "A4", L),
      step(5, "A4", L),
      step(6, "G4", R),
      step(8, "F4", L),
      step(9, "F4", L),
      step(10, "E4", R),
      step(11, "E4", R),
      step(12, "D4", L),
      step(13, "D4", L),
      step(14, "C4", R),
      step(16, "G4", R),
      step(17, "G4", R),
      step(18, "F4", L),
      step(19, "F4", L),
      step(20, "E4", R),
      step(21, "E4", R),
      step(22, "D4", L),
      step(24, "G4", R),
      step(25, "G4", R),
      step(26, "F4", L),
      step(27, "F4", L),
      step(28, "E4", R),
      step(29, "E4", R),
      step(30, "D4", L),
      step(32, "C4", R),
      step(33, "C4", R),
      step(34, "G4", R),
      step(35, "G4", R),
      step(36, "A4", L),
      step(37, "A4", L),
      step(38, "G4", R),
      step(40, "F4", L),
      step(41, "F4", L),
      step(42, "E4", R),
      step(43, "E4", R),
      step(44, "D4", L),
      step(45, "D4", L),
      step(46, "C4", R),
    ],
  },
  {
    id: "ode-to-joy",
    title: "Ode to Joy",
    kind: "Pieces",
    bpm: 92,
    loopBeats: 64,
    blurb: "Beethoven's theme, a fifth under the usual G line. One low note moves.",
    about:
      "Played a fifth under the G major line. It opens E, E, F, G, then G, F, E, D, then C, C, D, E. Bar 4 is a dotted E, D on the and, and a D that rings. The answer ends with a dotted D, C on the and, and a C that rings. The middle starts D, D, E, C, with eighths on E and F. One note is not on the pan. The low G before the theme comes back is played as the low A, still a step down from the D before it. The E after that A is tied over the next beat, so it is not struck again.",
    steps: [
      step(0, "E4", R),
      step(1, "E4", R),
      step(2, "F4", L),
      step(3, "G4", R),
      step(4, "G4", R),
      step(5, "F4", L),
      step(6, "E4", R),
      step(7, "D4", L),
      step(8, "C4", R),
      step(9, "C4", R),
      step(10, "D4", L),
      step(11, "E4", R),
      step(12, "E4", R),
      step(13.5, "D4", L),
      step(14, "D4", L),
      step(16, "E4", R),
      step(17, "E4", R),
      step(18, "F4", L),
      step(19, "G4", R),
      step(20, "G4", R),
      step(21, "F4", L),
      step(22, "E4", R),
      step(23, "D4", L),
      step(24, "C4", R),
      step(25, "C4", R),
      step(26, "D4", L),
      step(27, "E4", R),
      step(28, "D4", L),
      step(29.5, "C4", R),
      step(30, "C4", R),
      step(32, "D4", L),
      step(33, "D4", L),
      step(34, "E4", R),
      step(35, "C4", R),
      step(36, "D4", L),
      step(37, "E4", R),
      step(37.5, "F4", L),
      step(38, "E4", R),
      step(39, "C4", R),
      step(40, "D4", L),
      step(41, "E4", R),
      step(41.5, "F4", L),
      step(42, "E4", R),
      step(43, "D4", L),
      step(44, "C4", R),
      step(45, "D4", L),
      step(46, "A3", R),
      step(47, "E4", R),
      step(49, "E4", R),
      step(50, "F4", L),
      step(51, "G4", R),
      step(52, "G4", R),
      step(53, "F4", L),
      step(54, "E4", R),
      step(55, "D4", L),
      step(56, "C4", R),
      step(57, "C4", R),
      step(58, "D4", L),
      step(59, "E4", R),
      step(60, "D4", L),
      step(61.5, "C4", R),
      step(62, "C4", R),
    ],
  },
  {
    id: "frere-jacques",
    title: "Frere Jacques",
    kind: "Pieces",
    bpm: 96,
    loopBeats: 32,
    blurb: "The French round in F. Six notes move onto notes this pan has.",
    about:
      "The first line is F, G, A, F, twice. The second line is written A, B-flat, and a high C that rings. B-flat is played as A, and that happens twice. The bells are eighths written C, D, C, B-flat, then A and F. High D is played as high C, and B-flat as A. That pair of moves happens twice, six notes in all. The last line is F, C, and an F that rings, twice.",
    steps: [
      step(0, "F4", L),
      step(1, "G4", R),
      step(2, "A4", L),
      step(3, "F4", L),
      step(4, "F4", L),
      step(5, "G4", R),
      step(6, "A4", L),
      step(7, "F4", L),
      step(8, "A4", L),
      step(9, "A4", L),
      step(10, "C5", R),
      step(12, "A4", L),
      step(13, "A4", L),
      step(14, "C5", R),
      step(16, "C5", R),
      step(16.5, "C5", R),
      step(17, "C5", R),
      step(17.5, "A4", L),
      step(18, "A4", L),
      step(19, "F4", L),
      step(20, "C5", R),
      step(20.5, "C5", R),
      step(21, "C5", R),
      step(21.5, "A4", L),
      step(22, "A4", L),
      step(23, "F4", L),
      step(24, "F4", L),
      step(25, "C4", R),
      step(26, "F4", L),
      step(28, "F4", L),
      step(29, "C4", R),
      step(30, "F4", L),
    ],
  },
  {
    id: "veni-emmanuel",
    title: "O come, O come, Emmanuel",
    kind: "Pieces",
    bpm: 80,
    loopBeats: 76,
    blurb: "The advent hymn in D. Three peaks move from B-flat to A.",
    about:
      "One verse of the soprano, moved down from E minor into D. It starts on F. Three times the line peaks on a B-flat this pan does not have, and that peak is played as A, one semitone lower. Those three A's are the only changes. The last note is a D, and it leads back to the F.",
    steps: [
      step(0, "F4", L),
      step(1, "A4", L),
      step(2, "A4", L),
      step(3, "A4", L),
      step(4, "G4", R),
      step(5, "A4", L),
      step(6, "A4", L),
      step(7, "G4", R),
      step(8, "F4", L),
      step(11, "G4", R),
      step(12, "A4", L),
      step(13, "F4", L),
      step(14, "D4", L),
      step(15, "F4", L),
      step(16, "G4", R),
      step(17, "E4", R),
      step(18, "D4", L),
      step(19, "C4", R),
      step(20, "D4", L),
      step(23, "G4", R),
      step(24, "G4", R),
      step(25, "D4", L),
      step(26, "D4", L),
      step(27, "E4", R),
      step(28, "F4", L),
      step(30, "E4", R),
      step(31, "D4", L),
      step(32, "C4", R),
      step(35, "F4", L),
      step(36, "G4", R),
      step(37, "A4", L),
      step(38, "A4", L),
      step(39, "A4", L),
      step(40, "G4", R),
      step(41, "A4", L),
      step(42, "A4", L),
      step(43, "G4", R),
      step(44, "F4", L),
      step(47, "C5", R),
      step(48, "C5", R),
      step(51, "A4", L),
      step(52, "A4", L),
      step(55, "A4", L),
      step(56, "G4", R),
      step(57, "A4", L),
      step(58, "A4", L),
      step(59, "G4", R),
      step(60, "F4", L),
      step(63, "G4", R),
      step(64, "A4", L),
      step(65, "F4", L),
      step(66, "D4", L),
      step(67, "F4", L),
      step(68, "G4", R),
      step(69, "E4", R),
      step(70, "D4", L),
      step(71, "C4", R),
      step(72, "D4", L),
      step(75, "D4", L),
    ],
  },
];

export function pretty(id) {
  const note = NOTES[id];
  return `${note.letter}${note.octave}`;
}

export function eventsOf(pattern) {
  const map = new Map();
  for (const step of pattern.steps) {
    let event = map.get(step.beat);
    if (!event) {
      event = { beat: step.beat, notes: [], hands: {} };
      map.set(step.beat, event);
    }
    event.notes.push(step.note);
    event.hands[step.note] = step.hand;
  }
  return [...map.values()]
    .sort((a, b) => a.beat - b.beat)
    .map((event, index) => ({ ...event, index }));
}

export function cellsOf(pattern) {
  const events = eventsOf(pattern);
  const cells = [];
  for (let beat = 0; beat < pattern.loopBeats; beat += 1) {
    const group = events.filter((event) => event.beat >= beat && event.beat < beat + 1);
    if (group.length === 0) cells.push({ rest: true, beat });
    else cells.push(...group);
  }
  return cells;
}

export function beatLabel(beat) {
  const inside = beat % 4;
  const count = Math.floor(inside) + 1;
  const fraction = Math.round((inside - Math.floor(inside)) * 2) / 2;
  if (fraction === 0.5) return `${count} and`;
  return String(count);
}
